### ISSUE TITLE
"Always on top" don't work correctly on Windows 10

### ISSUE THREAD

**Issue by faiberg** [bornova/numara-calculator#102]
Hello! Thanks for great application! 
Version 5.6.0.  (x64)
Windows 10 Pro.
When I turn on the “Always on top” option, the window immediately falls to the background and never comes back.
Restarting the application does not solve the problem. A single tap on any other window is enough and Numara falls to the background again.

**Comment by bornova** [comment]
Hi @faiberg,
I am not able to reproduce the issue on my Win 10 PC. Here is how it behaves on my end (sorry for the horrible video quality):

https://github.com/user-attachments/assets/215ad1fb-92e8-45bd-9c9b-b6f489b42515

Do you mind taking a look at the logs and see if there are any error messages there?

![image](https://github.com/user-attachments/assets/a9fc05a7-8463-40cb-8e35-a979d89127ff)

**Comment by faiberg** [comment]
Hi.
Here is a log file. With no errors.
 
[main.log](https://github.com/user-attachments/files/17655368/main.log)

**Comment by faiberg** [comment]
Here is a video:

https://github.com/user-attachments/assets/eb63a7d4-8a5d-4b74-9600-80e6c30fe6b8

**Comment by faiberg** [comment]
After several experiments with clean installations in virtual machines, I have to admit that the problem is most likely related to the settings and plugins of my operating system specifically. 
I think we can close this issue.
"Thanks for your cooperation" (C)

**Comment by faiberg** [comment]
I think I've finally found what's causing the problem!
It doesn't work as expected if the systemexplorer.net application is running in the system tray at the same time.
Maybe someone will find this useful.

**Comment by bornova** [comment]
Thanks @faiberg for reporting!
