### ISSUE TITLE
Unable to auto update since 3.15.3

### ISSUE THREAD

**Issue by reddyshyam** [bornova/numara-calculator#12]
Hi,

Good day! Great app there! 🙏 Thank you.

Since the above version, auto update doesnot happen. I get the following errors. Hope this helps.

---

![Screenshot 2022-09-21 124619](https://user-images.githubusercontent.com/12392746/191440096-39aa7861-9ea1-4f93-b0ab-4d0cb3c00b5a.png)

---

![Screenshot 2022-09-21 125911](https://user-images.githubusercontent.com/12392746/191442134-36fb3f79-44db-4f40-b602-3f420a6f53a0.png)

---

![Screenshot 2022-09-21 124742](https://user-images.githubusercontent.com/12392746/191440131-3e5e6284-1d97-464b-aba1-19984360ed16.png)

---

I am Windows 10 Pro 64 bit (21H2 19044.2006) if that helps. Assuming an issue with that particular version, I fully installed 3.15.5 and today when I saw the update, tried auto updating and again saw the above errors. Hence reporting.

**Comment by bornova** [comment]
Hi @reddyshyam,
Thank you for reporting.  I don't have a Win 10 machine but I will setup a VM to try to replicate the issue.  However, I did try a new install of v3.15.3 and v3.15.5 on my Windows 11 and macOS machines.   Both updated to latest version without issues.

Are you behind a proxy server or a VPN by any chance?  I haven't run into this issue before so I am thinking if it is a network issue on your end.

**Comment by bornova** [comment]
OK.  Let me dig a little deeper into it.  It takes me a few minutes to setup a VM so not a big deal for me. Hopefully I can replicate the issue and find the root cause.

**Comment by bornova** [comment]
No. The app is built using Electron which includes its own Chromium and Node.js (that's why the app size is 80+ MB).  It does not depend on any external browsers.

**Comment by reddyshyam** [comment]
> No. The app is built using Electron which includes its own Chromium and Node.js (that's why the app size is 80+ MB). It does not depend on any external browsers.

Oh! Any way to clear its cache?

**Comment by bornova** [comment]
You can try an app reset as shown below.  Reinstalling the app should also clear the cache.  To be sure, you can try uninstalling the app and doing a clean install of [v3.16.0](https://github.com/bornova/numara-calculator/releases/tag/v3.16.0) and then see if it auto updates to 3.16.1?

![image](https://user-images.githubusercontent.com/35872220/191568038-e5dca5d0-11cb-4ed4-a394-75c789905734.png)

**Comment by reddyshyam** [comment]
> You can try an app reset as shown below. Reinstalling the app should also clear the cache. To be sure, you can try uninstalling the app and doing a clean install of [v3.16.0](https://github.com/bornova/numara-calculator/releases/tag/v3.16.0) and then see if it auto updates to 3.16.1?
> 
> ![image](https://user-images.githubusercontent.com/35872220/191568038-e5dca5d0-11cb-4ed4-a394-75c789905734.png)

I can do un-install and re-install but I will lose my settings. Is there any way, I can export and import the settings back?

**Comment by reddyshyam** [comment]
I tried removing and fresh installation of 3.16 and tried auto update. For some reason update gets really slow, eventually it hit 100% and then this above errors pop up. I cleared then error and surprisingly restart option came up. Finally I could auto update. :)

Not sure why it takes couple of minutes to download an update though. I am on a 100mbps line and 1GB file downloads in less than 5 minutes. So net speeds is not an issue.

**Comment by bornova** [comment]
Hi @reddyshyam,
I was not able to replicate the issue on Windows 10 VM machine.  However a quick search came up with the following:

https://github.com/electron-userland/electron-builder/issues/4987 for the initial issue you reported. This seems to be rare I think.  I can try to patch it with he solution proposed there but I am hesitant and wonder if it would cause other issues since it has worked pretty well for me and others for a while now.

Slow download issue is here: https://github.com/electron-userland/electron-builder/issues/5537.  Some are suggesting having too many releases slows down the downloads.  Not sure why that could be but I will remove most of the older releases (there are 100 of them) and see if that makes a difference.

**Comment by reddyshyam** [comment]
> Hi @reddyshyam, I was not able to replicate the issue on Windows 10 VM machine. However a quick search came up with the following:
> 
> [electron-userland/electron-builder#4987](https://github.com/electron-userland/electron-builder/issues/4987) for the initial issue you reported. This seems to be rare I think. I can try to patch it with he solution proposed there but I am hesitant and wonder if it would cause other issues since it has worked pretty well for me and others for a while now.
> 
> Slow download issue is here: [electron-userland/electron-builder#5537](https://github.com/electron-userland/electron-builder/issues/5537). Some are suggesting having too many releases slows down the downloads. Not sure why that could be but I will remove most of the older releases (there are 100 of them) and see if that makes a difference.

@bornova, that looks like the case with us but please do not do anything or delete the releases. Mine looks like isolatated incident and can always re-install a new update. No point wasting your time on this one.

Thanks again. 👍

**Comment by bornova** [comment]
Sounds good.  Thanks for the feedback and let me know if you have any other questions.
