### ISSUE TITLE
Keyboard shortcut to clear sheet

### ISSUE THREAD

**Issue by Reyhn3** [bornova/numara-calculator#14]
A keyboard shortcut like e.g. Ctrl + N to clear the sheet would be appreciated.

**Comment by bornova** [comment]
Hi @Reyhn3,
Thanks for the feedback.  The shortcut you are looking for is already implemented as Ctrl/Cmd + D.  Sorry for lack of documentation on this repo.  I should really invest some time into putting one together for things like these.

**Comment by Reyhn3** [comment]
Great!
The D-key was not intuitive, but I'll buy it.😃

**Comment by bornova** [comment]
Ctrl + N was used at some point to open a new calculator window but that functionality was removed due to calculation persistence issues between windows.  Hence , the Ctrl + D :smile:
