### ISSUE TITLE
Notification/alerts at top instead of bottom

### ISSUE THREAD

**Issue by vzeazy** [bornova/numara-calculator#18]
Hey @bornova,

Me again. :)

Suggestion for the UI. May be better to have the alerts/notifications up top of the interface. Find that when I'm working in the calc in rapid succession, the alerts impact my ability to interact with the input area.

Thanks again for the wonderful app.

**Comment by bornova** [comment]
Hi @vzeazy 
I have released v13.9.0 which includes the option to change the location of the notification bar. You can find this option in settings. Please let me know if this works for you.

Thank you!

**Comment by vzeazy** [comment]
Thanks again for the quick update to the program. The new option is perfect. Still using it on a daily basis 🙏
