### ISSUE TITLE
Linux Wayland support for display scaling

### ISSUE THREAD

**Issue by ntzb** [bornova/numara-calculator#19]
Hi,
first off, Numara is amazing! thanks for developing it.
using it on ubuntu with gnome and wayland, if selecting fractional display scaling (125%) the text is blurry:
https://i.imgur.com/R1ITdBG.png
it's the website rendering, vs the app rendering.
I suspect it's because of a lack of wayland support, can you add support for it?

**Comment by bornova** [comment]
Hi @ntzb!
Thanks you for the feedback.  Looks like Electron (what Numara is built on) supports Wayland but you may need to run Numara with some flags.  It seems the easiest way to do that is to set a configuration file on your system.  Take a look at this:
https://wiki.archlinux.org/title/wayland#Electron

Also here:
https://unix.stackexchange.com/questions/736187/how-to-globally-set-all-electron-apps-to-have-enable-features-useozoneplatform

Let me know if this helps.  Unfortunately there is no other way for me to support it at the moment.

**Comment by ntzb** [comment]
@bornova thanks for the quick reply!
seems like the suggestion solutions/workarounds will work.
I'll close this for now, as fractional scaling causes a lot of other problems I'd like to avoid.
