### ISSUE TITLE
add linux build

### ISSUE THREAD

**Issue by johannesjh** [bornova/numara-calculator#2]
would you welcome a pull request that builds a linux package? 

electron builder seems to support appimage and snap (but not flatpak).
https://www.electron.build/configuration/linux

**Comment by bornova** [comment]
Hi @johannesjh,
Thank you for your interest! The reason I haven't included any Linux builds is because I don't have a linux machine to test Numara on :disappointed:.  Numara started as a personal project. At the time Mac and Windows versions were all I needed.  However, if more people such as yourself start using it, it makes sense to support more operating systems.

I am definitely open to supporting Linux.  However, before doing so, I would like to switch auto updates to use GitHub releases instead of my personal server on numara.io.  This is where I keep latest macOS and Windows builds.  I will start working on switching and once done I will take you up on your PR request 😃

**Comment by johannesjh** [comment]
I found that electron-builder builds just fine on linux: the following commands built functioning packages that I could install and use. This required no code changes whatsoever. Awesome!

```bash
npm install
npm dist
cd dist

# to install and run the snap package:
snap install --dangerous ./numara_2.19.9_amd64.snap && snap run numara

# to run the appimage:
./Numara-2.19.9.AppImage
```

screenshot of numara running from snap package:
![Screenshot from 2021-02-21 10-52-45](https://user-images.githubusercontent.com/581188/108621457-f9056800-7432-11eb-8ef2-0f37f3533963.png)

To improve desktop integration, the following would be nice:
* window decorations (at least a close button)
* keyboard shortcuts Ctrl+Q for quit, Ctrl+W for close-window

regarding the update server: yes, makes sense (to avoid putting load on your server). Note: A github ci workflow could build the apps and upload build artifacts to github releases. I created such a workflow just recently https://github.com/johannesjh/fava-gtk/blob/main/.github/workflows/ci.yml

**Comment by johannesjh** [comment]
This commit https://github.com/johannesjh/numara-calculator/commit/251f57f5bb2207e318e491c44db943332d27dded implements a github ci workflow that builds all three platforms. I think this should make it easy for you to add automated builds. 

Note: I temporarily disabled package publishing because I did not want to set up the required credentials for publishing packages in according package repositories or on github. This change is in package.json, where I called electron-builder with an additional option like this: `electron-builder --publish never`. You can re-enable package publishing by removing the `--publish never` option.

**Comment by bornova** [comment]
Hi @johannesjh,
Thank you for testing Numara on Linux!  Great to see it works without issues there. I was able to switch to publishing to GitHub releases for auto updates using electron-builder as you suggested.  I also added the Linux builds (AppImage and .deb) you asked for.  Except for the Snap build. It kept giving me errors during build but I am looking into that. Also keep in mind the .deb build does not support auto updates. I have released the latest version as 3.0.0.

I added the same header I used for Windows version to the linux build.  You now have minimize/maximize and close actions available.  Not sure why the Ctrl+Q and Ctrl+W are not working though.  I thought they were OS specific. Maybe an Electron issue?  Cmd+Q on MacOS and Ctrl+W on Windows 10 works as expected on my end.  If not, I can register them using Mousetrap.

Lastly, using GitHub actions may be the way to go in the future.  Thank you so much for sharing your work on this! and again thanks for all your suggestions!

**Comment by johannesjh** [comment]
the appimage worked perfectly in my experience. i think we can close this issue. thank you!

(as a note for future reference: I installed the [app image launcher](https://github.com/TheAssassin/AppImageLauncher) which helped install the app images into the desktop environment, i.e., create a .desktop file for convenient launching of the app).

**Comment by bornova** [comment]
Hi @johannesjh,
Thank you for your suggestions!  Please let me know if you find any other issues or have other suggestions.
