### ISSUE TITLE
function hex return error result

### ISSUE THREAD

**Issue by gagmeng** [bornova/numara-calculator#22]
Hex(123456) return NaNe240", the expected return is 0x1e240.
Thanks!

**Comment by bornova** [comment]
Hi @gagmeng! Looks like a bug in the output formatting.  The formatter function is processing the answer (0x1e240) as if it is exponential notation and trying to format the value before the 'e' as a number but of course it is `NaN`.  I will release a fix on the next update shortly. Thank you for reporting!

**Comment by bornova** [comment]
Just released v4.0.7 (https://github.com/bornova/numara-calculator/commit/5e30d6d8b4d3668dde95deae926d10393edee82d) with the fix. Thank you!

**Comment by gagmeng** [comment]
Nice job. Thanks for your quick fix.
