### ISSUE TITLE
Does it support conversion between hex numbers and decimal numbers in signed format?

### ISSUE THREAD

**Issue by gagmeng** [bornova/numara-calculator#24]
For example:
hex number 0xFFFF convert to -1.
decimal number -1 convert to 0xFFFF or 0xFFFFFFFF acording our needed data type(INT16 INT32 or INT64).
Thanks.

**Comment by bornova** [comment]
Hi @gagmeng,
Yes, you can use the word size suffix (i8, i16, i32) when you go from hex to decimal.  I forgot to mention in my last answer, but Numara automatically tries to convert hex/oct/bin to decimals so no need to use the `number` function but it's there if you need it.  For example, you can simply write:
```
0xFFi8    // -1
0xFFFFi16    // -1
0xFFFFFFFFi32    // -1
```
Other way around, you can use the [`format`](https://mathjs.org/docs/reference/functions/format.html) function:
```
format(-1, {notation: "hex", wordSize: 8})    // 0xFFi8
format(-1, {notation: "hex", wordSize: 16})    // 0xFFFFi16
format(-1, {notation: "hex", wordSize: 32})    // 0xFFFFFFFFi32
```

**Comment by gagmeng** [comment]
format doesn't work in numara, it gets error.
Best regard,
gagmeng

**Comment by bornova** [comment]
Do you mind sharing the error please?  I am not seeing any errors on my end using Windows 10:

![image](https://github.com/bornova/numara-calculator/assets/35872220/43e5568b-58c8-469d-8e9b-1f7944476354)

Seems to be ok on the web as well:

![image](https://github.com/bornova/numara-calculator/assets/35872220/1319ed01-8551-418b-ad62-a71fc72a0a54)

**Comment by gagmeng** [comment]
using Win10.
![QQ截图20230924230446](https://github.com/bornova/numara-calculator/assets/13564117/e8926a37-caca-4453-affe-29da55ee7a2a)

**Comment by bornova** [comment]
Hmm, that's odd. If you click on Error what does it say? It may give me a clue. Also, are you using the default settings or have you made any changes?

**Comment by gagmeng** [comment]
![QQ截图20230925011622](https://github.com/bornova/numara-calculator/assets/13564117/b79e1003-f162-4031-9fa6-642fd4c5f0e1)

**Comment by gagmeng** [comment]
It works fine when reset the settings to default.

**Comment by bornova** [comment]
Do you remember which setting was changed when the error occurred?  The issue maybe related to that setting.

**Comment by gagmeng** [comment]
I can't  confirm which configuration items have been modified.
