### ISSUE TITLE
Space means multiply in this equation?

### ISSUE THREAD

**Issue by gagmeng** [bornova/numara-calculator#25]
https://github.com/bornova/numara-calculator/assets/13564117/e79ccb59-5637-48ac-871b-a3e0adf7ad1f

As shown in above video, the space do the multiply operation.

Best regards,
gagmeng

**Comment by bornova** [comment]
Hi @gagmeng,
I know it seems unnatural in some cases but that is the intended behavior.  You can read more about this 'implicit multiplication' behavior here: https://mathjs.org/docs/expressions/syntax.html#implicit-multiplication

Thank you!
