### ISSUE TITLE
Is the display duration of the pop-up message configurable

### ISSUE THREAD

**Issue by gagmeng** [bornova/numara-calculator#26]
When copying the calc result, is the display duration of the pop-up message configurable?

https://github.com/bornova/numara-calculator/assets/13564117/87047992-6a4c-445c-a98f-159f24bbd966

Best regards,
gagmeng

**Comment by bornova** [comment]
Hi @gagmeng,
Yes, there is a setting for notification duration (default is 5 seconds):

![image](https://github.com/bornova/numara-calculator/assets/35872220/29f60907-c60b-4348-9bd7-b6f09c1bb8af)
