### ISSUE TITLE
Unable to plot

### ISSUE THREAD

**Issue by Boldan** [bornova/numara-calculator#27]
![image](https://github.com/bornova/numara-calculator/assets/7620601/72bbca66-13c7-4784-a933-56c6b1d79f34)

This issue appeared in V4.1.0

**Comment by bornova** [comment]
Hi @Boldan,
Thank you for reporting the issue.  It is indeed a bug.  It seems `esbuild` is not able to handle the default export of `function-plot` package.  I am surprised I didn't catch it during testing but will try to release a fix ASAP.  In the meantime, feel free to downgrade to v4.0.8 if possible.

**Comment by bornova** [comment]
Hi @Boldan,
Just released [v4.1.1](https://github.com/bornova/numara-calculator/releases/tag/v4.1.1) with the fix.  Please let me know if you find anything else that doesn't look right and thank you for reporting!

**Comment by Boldan** [comment]
Excellent, the repair speed is so fast

**Comment by Boldan** [comment]
I have a suggestion to see if you can use the tab key as easily in Numrar as you do in JetBrains, where it can jump between the right positions

**Comment by Boldan** [comment]
> I have a suggestion to see if you can use the Tab key as easily in Numara as you do in JetBrains, where it can jump between the right positions

If it can be achieved, it is very practical

**Comment by bornova** [comment]
Hi @Boldan, I am not familiar with JetBrains.  Can you elaborate on your request please?

**Comment by Boldan** [comment]
> Hi @Boldan, I am not familiar with JetBrains.  Can you elaborate on your request please?

f(x)=x^2+1
Take the above function as an example: when you enter f(x), the cursor stays behind x, and when you press the Tab key, the cursor moves after ).
When you type x^2, it is displayed as x², which is more intuitive.
Right-click to add a copy as TeX or LaTeX.
I'm very sorry, my English is not good.I also put forward many suggestions that may be bad.

**Comment by Boldan** [comment]
> Hi @Boldan, I am not familiar with JetBrains.  Can you elaborate on your request please?

I'm not sure if this is a BUG.In the settings, it doesn't take effect when you set User local.

**Comment by bornova** [comment]
Hi @Boldan, English is not my native language either so you are fine.  And no suggestion is a bad suggestion 😃 I appreciate the feedback.

In Numara, tab key is used to either insert a tabbed space, or autocomplete the suggested function when typing.  I can look into adding the possibility to move the cursor after the `)` when tab key is pressed but can't promise it will be anytime soon.  In case you don't want the closing bracket to be automatically inserted, you can turn that feature off in Settings (Toggle 'Close matching brackets' to off).

Changing x^2 to x² while typing won't be supported I am afraid.  Changing that behavior could have broader implications.

Right-click to add a copy as TeX or LaTeX.  Now this I can do.  Math.js has a `toTex()` built in so should be fairly easy to implement.  However, I don't think it is that great.  You still need to take that latex string and pretty print it using another library so not sure if that's very useful.

**Comment by bornova** [comment]
> I'm not sure if this is a BUG.In the settings, it doesn't take effect when you set User local.

Setting the user locale only affects the way decimal points, thousand separators and dates are displayed.  For example, 1234.56 in US would be displayed as 1,234.56 where as in German it would be 1.234,56.  Same for dates, 10/25/2023 in US vs. 25.10.2023 in Germany.

**Comment by Boldan** [comment]
Okay, I understand. Thanks for your answer.

**Comment by Boldan** [comment]
> > I'm not sure if this is a BUG.In the settings, it doesn't take effect when you set User local.
> 
> Setting the user locale only affects the way decimal points, thousand separators and dates are displayed.  For example, 1234.56 in US would be displayed as 1,234.56 where as in German it would be 1.234,56.  Same for dates, 10/25/2023 in US vs. 25.10.2023 in Germany.
> 
> 

Okay, I understand. Thanks for your answer.

**Comment by Boldan** [comment]
> Hi @Boldan, English is not my native language either so you are fine.  And no suggestion is a bad suggestion 😃 I appreciate the feedback.
> 
> In Numara, tab key is used to either insert a tabbed space, or autocomplete the suggested function when typing.  I can look into adding the possibility to move the cursor after the `)` when tab key is pressed but can't promise it will be anytime soon.  In case you don't want the closing bracket to be automatically inserted, you can turn that feature off in Settings (Toggle 'Close matching brackets' to off).
> 
> Changing x^2 to x² while typing won't be supported I am afraid.  Changing that behavior could have broader implications.
> 
> Right-click to add a copy as TeX or LaTeX.  Now this I can do.  Math.js has a `toTex()` built in so should be fairly easy to implement.  However, I don't think it is that great.  You still need to take that latex string and pretty print it using another library so not sure if that's very useful.

Your analysis makes sense, I agree with your answer.

**Comment by Boldan** [comment]
![IMG_20231122_184435.jpg](https://github.com/bornova/numara-calculator/assets/7620601/b6db4250-a6bc-4063-b9cf-54f6f03c3c2e)

When you enter f (x) = x^2，Clicking plot will pop up this BUG.

**Comment by bornova** [comment]
Hi @Boldan,
This is a limitation of Math.js unfortunately. You must have BigNumber numeric output chosen under Calculator options in Settings:
![image](https://github.com/bornova/numara-calculator/assets/35872220/65870b6a-5171-482f-aa86-ebe12f6e947a)

I tried to offer a warning when this option is selected, which is available if you click the orange info icon:
![image](https://github.com/bornova/numara-calculator/assets/35872220/83daf739-98f5-4ccd-abb4-09caa3054247)

If you choose 'Number' as the numeric output in Settings then the plot should work as expected.

**Comment by Boldan** [comment]
I'm sure, I have set it up like yours.

**Comment by bornova** [comment]
Hi @Boldan,
I only get that error when BigNumber option is selected.  It seems to work as expected on my end.  If you are still having issues, resetting the app may resolve it.

https://github.com/bornova/numara-calculator/assets/35872220/f350212d-e06e-444a-9c3a-7cacbb51849a
