### ISSUE TITLE
The '-' is treated as minus when it starts a new line equation

### ISSUE THREAD

**Issue by gagmeng** [bornova/numara-calculator#28]
![QQ截图20231027161120](https://github.com/bornova/numara-calculator/assets/13564117/30cb56d0-a221-46b7-88a4-d1363accaf5b)
Best regards,
gagmeng

**Comment by bornova** [comment]
Hi @gagmeng,
That's the default behavior.  Calculations are continued on the next line if the line starts with an operator (+-/*).  However this can be turned off in Settings:

![image](https://github.com/bornova/numara-calculator/assets/35872220/0b785ca3-26d8-449e-acd1-fb705b3dde45)
