### ISSUE TITLE
Add delimiters to binary data view

### ISSUE THREAD

**Issue by gagmeng** [bornova/numara-calculator#31]
When converting data to binary, add delimiters for easier identification, just as below:

![无标题](https://github.com/bornova/numara-calculator/assets/13564117/872ca9b3-c041-4467-94e0-e547161e26fd)

**Comment by bornova** [comment]
Hi @gagmeng,
That's the default output from Math.js and I wouldn't want to change the default output as it might cause unexpected issues with other types of answers.

However, if you are up to it, you can define a custom function to format the output.  For example:
- Open `User functions and units` dialog ![image](https://github.com/bornova/numara-calculator/assets/35872220/4084dc3d-972e-4d89-b19f-043e8284684e)
- Add following function which adds a space after every 4th character
  ```javascript
  formatBin: (bin) => bin.replace(/(.{4})/g, "$1 ")
  ```
- Click save and now you can wrap the `bin` function with this custom formatter:
  ![image](https://github.com/bornova/numara-calculator/assets/35872220/ec0420bf-2560-4694-ac29-70dc7a658974)

Hope this helps!

By the way, please make sure to upgrade to v4.4.2 as previous versions had a bug where user defined functions textbox would not allow you to use the space key.

**Comment by gagmeng** [comment]
Maybe the function should like that:
`formatBin: (bin) => bin.replace(/.{1,4}(?=(.{4})*$)/g, "$& ")`
![QQ截图20240115092900](https://github.com/bornova/numara-calculator/assets/13564117/86ed73a8-aa49-4e52-ac10-23f08921ced3)
