### ISSUE TITLE
Updates are not installing

### ISSUE THREAD

**Issue by 1andro1** [bornova/numara-calculator#34]
Hello,

The program downloads the update, but it seems it cannot install it, as when the program is restarted the the programs starts to download the update again.

Best Regards,
Adriyan

**Comment by bornova** [comment]
Hi Adriyan,
Which OS are you using?

I know it's inconvenient but a fresh install might resolve the issue.

**Comment by 1andro1** [comment]
I am using Windows 11 but on Windows 10 the problem was also present. In fact, I am since recently with a Windows 11 so I installed the program also recently. Currently, I am with the newest version and I just installed a fresh copy per your suggestions. Once there is an update I will comment here whether the problem is present or it is gone.

Best Regards,
Adriyan

**Comment by bornova** [comment]
Hi Adriyan,
I don't have a Windows system to test the update feature so your input is greatly appreciated!  Please let me know if you have any issues during the next update.

Thank you,

**Comment by 1andro1** [comment]
Hello,

just now the app tried to updated to 4.4.3, but again unsuccessfully. The app shows a message: "updating Numara", but after that nothing happens.

I am currently with 4.4.2.

Best Regards,
Adriyan

**Comment by bornova** [comment]
Hi Adriyan,
Thanks for reporting again. I will need to dig a bit deeper into this one.  One last favor to ask:  If you click on Info icon, does it say 'Error checking for update.' or is it just stuck on Updating...?

![image](https://github.com/bornova/numara-calculator/assets/35872220/6428c95c-024f-4ce4-a808-c7e934d39309)

**Comment by bornova** [comment]
Hi Adriyan,
I have changed the installer type in v4.5.0 released yesterday.  Please try installing this version and let me know if you still have issues when the next update is released next week.  Thank you!

**Comment by 1andro1** [comment]
ok

**Comment by bornova** [comment]
Hi @1andro1,
Thanks for your patience.  I figured out the problem.  Since the Windows build is not signed with a certificate, it was throwing an error during auto update. It took couple iterations to test but latest version should now fix the issue (Tested on Window 11). You will need to update manually one last time.  Sorry for the inconvenience and please report if you have any other issues. Thank you!

**Comment by 1andro1** [comment]
Hi Timur,

now it is working! Many Thanks!
