### ISSUE TITLE
Sugestion possibility of tabs

### ISSUE THREAD

**Issue by 1andro1** [bornova/numara-calculator#35]
Hello,

would it be possible tabs to be implemented? The variables from one tab to be accessible from different tab? 

Best Regards,
Adriyan

**Comment by bornova** [comment]
Hi Adriyan!
This has been on my to do list for a while but I just haven't had time to implement it yet.  I will be working on it here and there but it's hard for me to give you an ETA at the moment.

Thank you!

**Comment by 1andro1** [comment]
It is not a problem. It is only a suggestion.

Many thanks for the great work!
