### ISSUE TITLE
Exponent limits in the results

### ISSUE THREAD

**Issue by 1andro1** [bornova/numara-calculator#4]
Hello,

I would like to thank you for the all your efforts which you invested and still investing in making the program and providing it to all to enjoy it.

I would like to give you a suggestion. It would be nice if a person can set  the limit at which the output to be changed in scientific notation. As example if I set the precision to 4 and the results is between 0.0001 and 0.000000000001 the result is shown as 0. It would be nice if the options is for both positive and negative scientific notations.

![image](https://user-images.githubusercontent.com/79647326/150589444-48240f14-1fb7-4785-aef4-9dd195a251ee.png)

Best Regards,
Adriyan

**Comment by bornova** [comment]
Hi @1andro1,
Thank you for the suggestion!  I have added the option to set upper and lower limits for exponents in settings. They used to default to `12` and `-12`.

With your example, you can now try setting lower exponent limit to `-3` let's say and the results should be:
```
0.0001 = 1e-4
0.000000000001 = 1e-12
```

You can now also choose to always use exponential notation by switchin on the `Always use exponential notation` option in settings.

I have released v3.10.0 with theses updates.  Please give it a try and let me know if this fulfills your request.

**Comment by 1andro1** [comment]
Great! Works like charm! Many Thanks!
