### ISSUE TITLE
How can I install Numara on linux

### ISSUE THREAD

**Issue by jcomello** [bornova/numara-calculator#45]
I noticed in the description that Numara is for Linux too.
And I saw in [this issue](https://github.com/bornova/numara-calculator/issues/2) that you guys created a snap package. 
Is Numara in snap store?

**Comment by bornova** [comment]
Hi @jcomello,
Numara is not in the snap store at the moment but Linux is supported:

For most Linux distros you can try using the `AppImage` build:
https://github.com/bornova/numara-calculator/releases/download/v4.5.4/Numara-4.5.4-x86_64.AppImage

For Debian based distros specifically, you can also use the `deb build:
https://github.com/bornova/numara-calculator/releases/download/v4.5.4/Numara-4.5.4-amd64.deb

**Comment by jcomello** [comment]
Thanks!
