### ISSUE TITLE
DevTools always open on start

### ISSUE THREAD

**Issue by ellsclytn** [bornova/numara-calculator#48]
Running numara 4.5.5 on Arch Linux (based on the `amd64.deb` package).

Whenever I launch numara, the Chrome/Electron DevTools will open with it. I couldn't spot any toggle for this, so I wondered if it's a bug.

**Comment by bornova** [comment]
Hi @ellsclytn,
That's interesting! Thank you for reporting.  The only way to open the developer tools should be by clicking the version number in the About dialog 9 times.  I had added that feature to help me troubleshoot errors but it should not be opening by itself.  I will look into it.

**Comment by bornova** [comment]
Hi @ellsclytn,
Can you please try v4.5.7? I removed code that opened the dev tools if the app I not packaged (ie. in development).  Hoping this fixes the issue.

**Comment by ellsclytn** [comment]
That's done it! Thanks so much.
