### ISSUE TITLE
feature request: underscore for last answer

### ISSUE THREAD

**Issue by Dialga** [bornova/numara-calculator#62]
Hi, can _ be added as an alias for the last answer? _ is used in python for the last result, and be shorter to type than ans.

Side question: what is the ds unit? I could not find any reference to ds in the wiki.

**Comment by bornova** [comment]
Hi @Dialga,
Thanks for the suggestion!  I will see if the `_` character conflicts with any built in function or syntax.  If not, should be easy to implement.

As for the `ds`, `d` is the abbreviation for `deci` with a value of 1e-1.  And `s` is short for seconds so `1 ds` is equal to` 0.1 s`.  For example, you can try `1 ds to s  // 0.1 s` 

There are many other prefixes like this.  I will update the documentation to include them.  In the meantime, you can refer to https://mathjs.org/docs/datatypes/units.html#prefixes for the complete list.

**Comment by bornova** [comment]
`_` is now available in [v5.1.0](https://github.com/bornova/numara-calculator/releases/tag/v5.1.0).  Thanks for the request and please let me know if you find any bugs.
