### ISSUE TITLE
newton (N) cannot be used as a unit.

### ISSUE THREAD

**Issue by breathiness** [bornova/numara-calculator#69]
![图片](https://github.com/bornova/numara-calculator/assets/11361630/f72534a4-ce7f-4b21-9789-5b7e0679de3a)

**Comment by bornova** [comment]
Hi @breathiness,
Thanks for reporting.  Looks like the `N` newton unit is being overridden by the N excel function.  I will release a fix as soon as possible.

**Comment by bornova** [comment]
Hi @breathiness,
I resolved the naming conflict  by adding a prefix to all Formulajs functions.  `N` unit and any other conflicting units should now work as expected in just released [v5.2.0](https://github.com/bornova/numara-calculator/releases/tag/v5.2.0)

**Comment by breathiness** [comment]
![图片](https://github.com/bornova/numara-calculator/assets/11361630/54a43594-9a06-4efa-bc38-4f7576a5b7c4)
Thank you! The new version is now working properly.

**Comment by bornova** [comment]
The screenshot made me realize the `N` syntax color was now incorrect.  So thanks for posting that.  I have fixed it in v5.2.1.

Let me know if you find anything else.  I will close this issue as resolved.
