### ISSUE TITLE
[feature request] - settings for decimal separator

### ISSUE THREAD

**Issue by icaine** [bornova/numara-calculator#7]
It would be nice to have an ability to set decimal separator for input numbers (at least switching between dot/comma).
As you can see on the pic below, most of the world actually uses comma as decimal separator. Which means that on localized keyboards from those green countries numpad dot key generates comma.
![obrazek](https://user-images.githubusercontent.com/1388807/152638211-bd01e552-2165-47eb-8f90-9d5e365bf9d4.png)

**Comment by bornova** [comment]
Hi @icaine,
Thank you for the suggestion! This is something I have wanted to implement from day one but unfortunately it is really tricky. This is mainly because Numara uses math.js for calculations and this causes conflict with some of the internal functions. For example, take `log(1000,10)` and let's say we used commas as decimal separators.  In this case, what should the correct answer be? `4` or `9.2104`?

**Comment by icaine** [comment]
Thats tricky indead.. I forgot that we can use functions:) But there might be a solution (unless i forgot another functionality that it can collide with too) - using semicolon `;` as arg separator. But i think that would probably complicate things - so maybe we can close this one?

**Comment by bornova** [comment]
I am afraid I won't be able to implement something that would work without issues with all the functions.  As you mentioned, using a different separator may break other functionality.  I also think this would be best implemented natively with math.js.  Let's close this one for now.  This one has been on my mind for a while but I just don't have the right solution right now.

**Comment by bornova** [comment]
Looks like math.js has an example of using custom seprators here: https://mathjs.org/examples/browser/custom_separators.html.html

I will play around with this in the next few days to see if I can incorporate something similar for Numara.

**Comment by bornova** [comment]
Hi @icaine ,
I just released [v3.11.1](https://github.com/bornova/numara-calculator/releases/tag/v3.11.1) with option to choose a locale.  And based on the locale, you can now use comma as a decimal separator.  However, as you mentioned, when using a locale with comma as decimal separator, you must use semicolon (;) as argument separator in functions.  To choose a locale that fits you, you can go to Settings and set the locale under Data & Time.

For example, if you choose German, you can now do:
```
123,45 + 5,3  // 128,75
```
and for functions you can do:
```
sum(1;2) // 3
```

Dates are also now displayed in chosen locale. Again, in German: `today // 8.2.2022` or in Italian: `today  // 8/2/2022` and so on.

I hope this is what you were looking for and please don't hesitate to report any bugs.  Thanks for the suggestion!
