### ISSUE TITLE
Sequential (n) addition in one string with result list

### ISSUE THREAD

**Issue by ropucyka** [bornova/numara-calculator#70]
Which formula will be for **446,00625+0,0125** 12 times and receive its result as solid answer with **custom** separator?
Example: 446,00625 + 0,0125 = 446.01875; 446.03125 ... an so on 12 times ?

**Comment by bornova** [comment]
Hi @ropucyka,
If your system locale doesn't uses commas as decimal separator, you would first need to change the locale setting to one that uses commas, such as German:

![image](https://github.com/bornova/numara-calculator/assets/35872220/04690035-2f0f-4bf6-98b8-69e997ae93d4)

Then, if you want to print the answers in one line, you can use an array, where each calculation is separated by `;`:
![image](https://github.com/bornova/numara-calculator/assets/35872220/6f82679f-29c6-4398-a9a9-2e7598f080bf)

If you need the sum of all in the array, you can do `sum(ans)` on the next line or `sum` in the same line:
![image](https://github.com/bornova/numara-calculator/assets/35872220/acf0fc0d-c949-4a65-ac99-ecf251d9bb22)

Hope this helps!

**Comment by ropucyka** [comment]
Mmm im not sure, its not helped. But thank You for so quick feedback.

**Comment by bornova** [comment]
May not be exactly what you are looking for, but I can suggest the `range` function.  You can define the start, end, and step values to generate the array.  You can also use the `resize` function to limit the size of the array to `n` numbers.

![image](https://github.com/bornova/numara-calculator/assets/35872220/ee32eddf-ba97-4fcd-8df6-5de4f830f437)

The end value can't be open ended though (100+) but you can define a large number here instead (I chose 1000 for example).

There is whole a lot more you can do with arrays and matrices.  You can read about here: https://mathjs.org/docs/datatypes/matrices.html

**Comment by ropucyka** [comment]
range(446.00625;1000;0.0125).resize([8]) =
[446.00625, 446.01875, 446.03125, 446.04375, _446.05625_, **446.06874999999997**, **446.08124999999995**, **446.09374999999994**]
It what needed. But wtf with last 3 results? It must just add 0.0125 to 446.05625 **??** _446.05625_+0.0125

**Comment by bornova** [comment]
Hi @ropucyka,
It is a [floating point round-off error](https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors).  One of the pitfalls of [working with numbers in javascript.](https://stackoverflow.com/questions/588004/is-floating-point-math-broken) If you open your browser's console and type `446.05625+0.0125` you would also get `446.06874999999997`.

One workaround is to wrap the calculation in [`fix`](https://mathjs.org/docs/reference/functions/fix.html) function and give it a decimal number of 5.  Here is what it all looks like:

![image](https://github.com/bornova/numara-calculator/assets/35872220/4cec21eb-e627-4175-a649-56e26b01ba95)

**Comment by ropucyka** [comment]
Now works well. Thank you.

**Comment by bornova** [comment]
No problem!  Closing this issue for now.  Can reopen if you have any other questions.  Thank you
