### ISSUE TITLE
Missing 'libuuid' on openSUSE

### ISSUE THREAD

**Issue by yardern** [bornova/numara-calculator#74]
Thanks for this great app!

I tried to install the rpm package to openSUSE (both Leap 15.6 and Tumbleweed 2024), got:

**nothing provides 'libuuid' needed by the to be installed numara-5.2.1-1.x86_64**

Searched in openSUSE and found that I have 'libuuid1' installed instead. It showed 'libuuid-devel' available but not installed.
What confuses me is that Fedora has 'libuuid', is the rpm meant for Fedora only?
How could I solve the problem please?

**Comment by bornova** [comment]
Hi @yardern,
I am no openSUSE expert by any means but I found a similar issue in another app:
https://github.com/BoostIO/BoostNote-App/issues/1063

I will implement the same fix in the next release and see if that resolves your issue.

**Comment by yardern** [comment]
Hi @bornova ,

Thank you so much for your quick action!
It is working like a charm!
