### ISSUE TITLE
Add the ability to quickly call the answer

### ISSUE THREAD

**Issue by breathiness** [bornova/numara-calculator#77]
Currently, the result of a call requires lineX, can you add a function to call the answer quickly?
You can refer to CalcNote on Android. Tap the line number to call the line.

https://github.com/user-attachments/assets/5527771b-8673-4f57-b7eb-7c1690e97ba2

**Comment by bornova** [comment]
Thanks again for the suggestion.  Now implemented in [v5.3.0](https://github.com/bornova/numara-calculator/releases/tag/v5.3.0). Please let me know if that works as intended.

**Comment by gagmeng** [comment]
amazing features.

**Comment by breathiness** [comment]
Thanks, the new version works fine on the Windows side.
![Clip_20240829_203926](https://github.com/user-attachments/assets/b495aef2-4036-413d-8abe-d525879acd95)
But a new bug has been discovered.

**Comment by bornova** [comment]
Hi @breathiness, calculations are evaluated line by line, top to bottom and in order. Since `line6` is called in line 5, it is not yet available. Hence the error.

**Comment by breathiness** [comment]
OK, thanks for the answer👍
