### ISSUE TITLE
Add the ability to calculate the interval between two dates

### ISSUE THREAD

**Issue by breathiness** [bornova/numara-calculator#81]
Now to calculate this data, I am using the date calculation that comes with Windows.
![Snipaste_2024-09-03_23-24-42](https://github.com/user-attachments/assets/710b0565-759b-466e-823b-b860216fd239)

**Comment by breathiness** [comment]
Well, thanks for the answer. Although I don't think there are many cases where someone just happens to come across the format “XXXX/XX/XX/XX-XXXX/XX/XX”. But it's not really a good idea to rule it out.
I can't think of any good solutions right now. Should this issues be turned off?

**Comment by bornova** [comment]
Feel free to close it for now while I explore options to improve the date time calculations.  Thanks for the feedback!

**Comment by skygate2012** [comment]
@bornova Can you make dates work with today/now? Currently it doesn't work due to them evaluating into a date.

**Comment by skygate2012** [comment]
Btw Soulver solves this with keywords
`days between 3 March and 30 May     | 88 days`
https://documentation.soulver.app/syntax-reference/dates/dates-and-times
