### ISSUE TITLE
Size of the line spacing

### ISSUE THREAD

**Issue by 1andro1** [bornova/numara-calculator#9]
Hello, 

many thanks for the wonderful application. I would like to ask you whether it is possible a variable line spacing to be implemented?

Best Regards,
Adriyan

**Comment by bornova** [comment]
Hi @1andro1, thank you for the suggestion!  I like the idea and should be able to implement that pretty easily.  I can give it a range similar to the Font Size option in Settings.  From Tiny to X-Large, Normal being the line height that's currently being used.  Would that work for you?

**Comment by 1andro1** [comment]
Sound great! Many thanks!

What else I can suggest is, that I write always the units for resistance with capatilized O: uOhm, mOhm, Ohm, kOhm, MOhm, GOhm. I do not know whether there is some standard how it should be written, but it looks better for me with capitalized O.

Best Regards,
Adriyan

**Comment by bornova** [comment]
I will start working on line hight adjustment option soon.

The units however are handled by math.js and I am not sure if I want to override the default behavior and possibly introduce bugs unintentionally.  I will do some digging into it tho to see if I can do anything to handle both lower and uppercase uses.

Thanks for the feedback!

**Comment by 1andro1** [comment]
Just tested the new versions. Everything works fine! Many thanks!
