### ISSUE TITLE
Wrap breaks numbers

### ISSUE THREAD

**Issue by Vanav** [bornova/numara-calculator#90]
Wrap in UI may split one number in two parts. It is better to wrap by words.

<img width="273" alt="firefox_0wZW2ROC0P" src="https://github.com/user-attachments/assets/e348f040-ddab-4d71-a6fa-7a7f9e816032">

**Comment by bornova** [comment]
Hi @Vanav,
Thanks for reporting!  This is now fixed in [v5.4.2](https://github.com/bornova/numara-calculator/releases/tag/v5.4.2)

**Comment by Vanav** [comment]
Wrap doesn't work at all in v5.4.2, if input is without spaces (like on my screenshot).
I think, wrap should work without spaces too, because spaces should be inserted manually, and are not required, so they are not commonly used.

**Comment by bornova** [comment]
Unfortunately it is not possible to wrap at specific characters such as `+ - / *`.  So in your example, only way to prevent the wrap at a random place (in the middle of 2000) is to allow breaks only for full words or scroll if one long line.  Which is what was implemented in v5.4.2

If no spaces are provided, then line won't wrap but will be scrolled to prevent wrapping in the middle of a word or number.  If a space is added, then line will wrap at that point.  

Although I don't have an immediate fix for what you are looking for, I will continue to explore ways to improve the line breaks.

**Comment by bornova** [comment]
Hi @Vanav,
Just released v5.5.0 with some improvements on line wrapping. Please let me know if this is now what you were expecting.

**Comment by Vanav** [comment]
Seems you have found a perfect solution! Thank you so much.
