### ISSUE TITLE
[Feature request] Set focus to new line on launch and remember window position

### ISSUE THREAD

**Issue by Vanav** [bornova/numara-calculator#94]
To start calculation quickly, it is useful, if user can start typing immediately. I suggest on launch: add new line to the end on input, if there is no new line, and move focus to it.

Test case:
1. Launch Numara
2. Type "2+2", got result.

Also, please, remember window position on screen on close, so window should not always launch on screen center.

**Comment by bornova** [comment]
Hi @Vanav,
Numara is supposed to start where the user left off when the app was closed but I see the editor is not being focused on start at the moment.  I will release a fix asap.

I like the idea of remembering the window position.  I will add this to the next release as well.  Thanks for the suggestion!

**Comment by bornova** [comment]
Line focus has been improved and remembering window position feature has now been implemented in v5.5.0.  Thanks for all the bug reports and suggestions!  Please let me know if you find more bugs or any regressions.

**Comment by Vanav** [comment]
Perfect, thank you!

**Comment by Vanav** [comment]
I've noticed that focus is still lost if minimize and then restore window.

**Comment by bornova** [comment]
Hi @Vanav,
Good catch! I will fix this in the next release. Thanks for reporting.

**Comment by bornova** [comment]
> I've noticed that focus is still lost if minimize and then restore window.

This should now be fixed in [v5.7.2](https://github.com/bornova/numara-calculator/releases/tag/v5.7.2)

**Comment by Vanav** [comment]
Thank you, all is working good!
