### ISSUE TITLE
currency rates drifting - no updates during app runtime

### ISSUE THREAD

**Issue by ntzb** [bornova/numara-calculator#98]
Hi, thanks for a super useful app.
I'm keeping Numara open in my PC all the time, and it seems that the currency rates only update once when the app starts up.
example:
https://imgur.com/tULMB2u

can you add a daily update? or a selectable update period (e.g. with a setInterval after startup)?

additionally, a small annoyance - the conversion is not detected unless using capital letters, can you allow detection of currencies for e.g. `1 usd in eur` and not only `1 USD in EUR`?

many thanks!

**Comment by bornova** [comment]
Hi @ntzb,
Good suggestion on the currency rates!  I can definitely look into adding a rate update interval to the settings.  But please note the rates are pulled from [floatrates.com](https://www.floatrates.com/daily/usd.json) and I don't know how often they update the rates.  It's definitely not real time.  In the meantime, toggling the currency Enabled switch in the settings will pull the latest rates.

As for currencies, either lowercase or uppercase letters were allowed prior to v5.4.0.  However, I found that some lowercase currency symbols clash with other units.  One example is `cup`, which is a unit of volume but can also be Cuban Pesos. Therefore, the decision was made to use uppercase instead.  I use currency conversion all the time so I understand the inconvenience but I would like to keep that as is.

Thanks for the feedback!

**Comment by bornova** [comment]
Hi @ntzb,
Just released [v5.6.0](https://github.com/bornova/numara-calculator/releases/tag/v5.6.0) with the option to set currency rate update interval.  Please let me know if this works for you.

**Comment by ntzb** [comment]
wow, lightning fast! thanks a lot!
I just updated, will see how it behaves, and let you know of any issues.

about the currency letter case - I see your point.
